# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(['dafne.py'],
             pathex=['C:\\dafne\\dafne'],
             binaries=[('libpotrace-0.dll', '.')],
             datas=[('LICENSE', '.'), ('ui\\images\\*', 'ui\\images')],
			 hiddenimports = ['pydicom', 
				'SimpleITK',
				'potrace.bezier',
				'potrace.agg',
				'potrace.agg.curves',
				'tensorflow',
				'keras',
				'skimage',
				'nibabel',
				'dl'],
             hookspath=['.'],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='dafne',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
		  icon='dafne_icon.ico',
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='dafne')
