# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModelBrowser.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModelBrowser(object):
    def setupUi(self, ModelBrowser):
        ModelBrowser.setObjectName("ModelBrowser")
        ModelBrowser.resize(1024, 768)
        self.verticalLayout = QtWidgets.QVBoxLayout(ModelBrowser)
        self.verticalLayout.setObjectName("verticalLayout")
        self.model_tree = QtWidgets.QTreeWidget(ModelBrowser)
        self.model_tree.setObjectName("model_tree")
        self.verticalLayout.addWidget(self.model_tree)
        self.details_table = QtWidgets.QTableWidget(ModelBrowser)
        self.details_table.setEnabled(True)
        self.details_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.details_table.setObjectName("details_table")
        self.details_table.setColumnCount(2)
        self.details_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.details_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.details_table.setHorizontalHeaderItem(1, item)
        self.details_table.horizontalHeader().setStretchLastSection(True)
        self.details_table.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.details_table)
        self.buttonBox = QtWidgets.QDialogButtonBox(ModelBrowser)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ModelBrowser)
        self.buttonBox.accepted.connect(ModelBrowser.accept) # type: ignore
        self.buttonBox.rejected.connect(ModelBrowser.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ModelBrowser)

    def retranslateUi(self, ModelBrowser):
        _translate = QtCore.QCoreApplication.translate
        ModelBrowser.setWindowTitle(_translate("ModelBrowser", "Dafne Model Browser"))
        self.model_tree.headerItem().setText(0, _translate("ModelBrowser", "Models"))
        item = self.details_table.horizontalHeaderItem(0)
        item.setText(_translate("ModelBrowser", "Name"))
        item = self.details_table.horizontalHeaderItem(1)
        item.setText(_translate("ModelBrowser", "Info"))
