# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'supportDataViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SupportDataViewerDialog(object):
    def setupUi(self, SupportDataViewerDialog):
        SupportDataViewerDialog.setObjectName("SupportDataViewerDialog")
        SupportDataViewerDialog.resize(723, 609)
        self.gridLayout = QtWidgets.QGridLayout(SupportDataViewerDialog)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 5, 1, 1)
        self.imageViewerParent = QtWidgets.QWidget(SupportDataViewerDialog)
        self.imageViewerParent.setMinimumSize(QtCore.QSize(500, 500))
        self.imageViewerParent.setObjectName("imageViewerParent")
        self.gridLayout.addWidget(self.imageViewerParent, 0, 0, 1, 6)
        self.roiGroup = QtWidgets.QGroupBox(SupportDataViewerDialog)
        self.roiGroup.setObjectName("roiGroup")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.roiGroup)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout.addWidget(self.roiGroup, 0, 7, 2, 1)
        self.transposeButton = QtWidgets.QToolButton(SupportDataViewerDialog)
        self.transposeButton.setMinimumSize(QtCore.QSize(48, 48))
        self.transposeButton.setBaseSize(QtCore.QSize(64, 64))
        self.transposeButton.setIconSize(QtCore.QSize(32, 32))
        self.transposeButton.setObjectName("transposeButton")
        self.gridLayout.addWidget(self.transposeButton, 1, 1, 1, 1)
        self.mirrorXButton = QtWidgets.QToolButton(SupportDataViewerDialog)
        self.mirrorXButton.setMinimumSize(QtCore.QSize(48, 48))
        self.mirrorXButton.setIconSize(QtCore.QSize(32, 32))
        self.mirrorXButton.setObjectName("mirrorXButton")
        self.gridLayout.addWidget(self.mirrorXButton, 1, 3, 1, 1)
        self.rotateButton = QtWidgets.QToolButton(SupportDataViewerDialog)
        self.rotateButton.setMinimumSize(QtCore.QSize(48, 48))
        self.rotateButton.setIconSize(QtCore.QSize(32, 32))
        self.rotateButton.setObjectName("rotateButton")
        self.gridLayout.addWidget(self.rotateButton, 1, 2, 1, 1)
        self.mirrorYButton = QtWidgets.QToolButton(SupportDataViewerDialog)
        self.mirrorYButton.setMinimumSize(QtCore.QSize(48, 48))
        self.mirrorYButton.setIconSize(QtCore.QSize(32, 32))
        self.mirrorYButton.setObjectName("mirrorYButton")
        self.gridLayout.addWidget(self.mirrorYButton, 1, 4, 1, 1)
        self.transferButton = QtWidgets.QToolButton(SupportDataViewerDialog)
        self.transferButton.setMinimumSize(QtCore.QSize(0, 48))
        self.transferButton.setObjectName("transferButton")
        self.gridLayout.addWidget(self.transferButton, 1, 6, 1, 1)

        self.retranslateUi(SupportDataViewerDialog)
        QtCore.QMetaObject.connectSlotsByName(SupportDataViewerDialog)

    def retranslateUi(self, SupportDataViewerDialog):
        _translate = QtCore.QCoreApplication.translate
        SupportDataViewerDialog.setWindowTitle(_translate("SupportDataViewerDialog", "Dialog"))
        self.roiGroup.setTitle(_translate("SupportDataViewerDialog", "ROIs to transfer"))
        self.transposeButton.setText(_translate("SupportDataViewerDialog", "T"))
        self.mirrorXButton.setText(_translate("SupportDataViewerDialog", "Mx"))
        self.rotateButton.setText(_translate("SupportDataViewerDialog", "R"))
        self.mirrorYButton.setText(_translate("SupportDataViewerDialog", "My"))
        self.transferButton.setText(_translate("SupportDataViewerDialog", "Transfer"))
