# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toolbox.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SegmentationToolbox(object):
    def setupUi(self, SegmentationToolbox):
        SegmentationToolbox.setObjectName("SegmentationToolbox")
        SegmentationToolbox.resize(256, 479)
        self.centralwidget = QtWidgets.QWidget(SegmentationToolbox)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.classification_combo = QtWidgets.QComboBox(self.centralwidget)
        self.classification_combo.setObjectName("classification_combo")
        self.verticalLayout.addWidget(self.classification_combo)
        self.ROI_group = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ROI_group.sizePolicy().hasHeightForWidth())
        self.ROI_group.setSizePolicy(sizePolicy)
        self.ROI_group.setObjectName("ROI_group")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.ROI_group)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.roi_combo = QtWidgets.QComboBox(self.ROI_group)
        self.roi_combo.setObjectName("roi_combo")
        self.horizontalLayout.addWidget(self.roi_combo)
        self.roi_add_button = QtWidgets.QToolButton(self.ROI_group)
        self.roi_add_button.setObjectName("roi_add_button")
        self.horizontalLayout.addWidget(self.roi_add_button)
        self.roi_remove_button = QtWidgets.QToolButton(self.ROI_group)
        self.roi_remove_button.setObjectName("roi_remove_button")
        self.horizontalLayout.addWidget(self.roi_remove_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.ROI_group)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.subroi_combo = QtWidgets.QComboBox(self.ROI_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subroi_combo.sizePolicy().hasHeightForWidth())
        self.subroi_combo.setSizePolicy(sizePolicy)
        self.subroi_combo.setObjectName("subroi_combo")
        self.horizontalLayout_2.addWidget(self.subroi_combo)
        self.subroi_add_button = QtWidgets.QToolButton(self.ROI_group)
        self.subroi_add_button.setObjectName("subroi_add_button")
        self.horizontalLayout_2.addWidget(self.subroi_add_button)
        self.subroi_remove_button = QtWidgets.QToolButton(self.ROI_group)
        self.subroi_remove_button.setObjectName("subroi_remove_button")
        self.horizontalLayout_2.addWidget(self.subroi_remove_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.ROI_group)
        self.autosegment_button = QtWidgets.QPushButton(self.centralwidget)
        self.autosegment_button.setObjectName("autosegment_button")
        self.verticalLayout.addWidget(self.autosegment_button)
        self.knots_group = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.knots_group.sizePolicy().hasHeightForWidth())
        self.knots_group.setSizePolicy(sizePolicy)
        self.knots_group.setObjectName("knots_group")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.knots_group)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.addknot_button = QtWidgets.QPushButton(self.knots_group)
        self.addknot_button.setCheckable(True)
        self.addknot_button.setChecked(False)
        self.addknot_button.setAutoExclusive(False)
        self.addknot_button.setObjectName("addknot_button")
        self.verticalLayout_3.addWidget(self.addknot_button)
        self.removeknot_button = QtWidgets.QPushButton(self.knots_group)
        self.removeknot_button.setCheckable(True)
        self.removeknot_button.setAutoExclusive(False)
        self.removeknot_button.setObjectName("removeknot_button")
        self.verticalLayout_3.addWidget(self.removeknot_button)
        self.removeall_button = QtWidgets.QPushButton(self.knots_group)
        self.removeall_button.setObjectName("removeall_button")
        self.verticalLayout_3.addWidget(self.removeall_button)
        self.verticalLayout.addWidget(self.knots_group)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        SegmentationToolbox.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SegmentationToolbox)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 256, 28))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        SegmentationToolbox.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SegmentationToolbox)
        self.statusbar.setObjectName("statusbar")
        SegmentationToolbox.setStatusBar(self.statusbar)
        self.actionSave_masks = QtWidgets.QAction(SegmentationToolbox)
        self.actionSave_masks.setObjectName("actionSave_masks")
        self.actionImport_ROIs = QtWidgets.QAction(SegmentationToolbox)
        self.actionImport_ROIs.setObjectName("actionImport_ROIs")
        self.actionExport_ROI_file = QtWidgets.QAction(SegmentationToolbox)
        self.actionExport_ROI_file.setObjectName("actionExport_ROI_file")
        self.actionImport_masks = QtWidgets.QAction(SegmentationToolbox)
        self.actionImport_masks.setObjectName("actionImport_masks")
        self.menuFile.addAction(self.actionImport_ROIs)
        self.menuFile.addAction(self.actionExport_ROI_file)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionImport_masks)
        self.menuFile.addAction(self.actionSave_masks)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(SegmentationToolbox)
        QtCore.QMetaObject.connectSlotsByName(SegmentationToolbox)

    def retranslateUi(self, SegmentationToolbox):
        _translate = QtCore.QCoreApplication.translate
        SegmentationToolbox.setWindowTitle(_translate("SegmentationToolbox", "MainWindow"))
        self.ROI_group.setTitle(_translate("SegmentationToolbox", "ROI"))
        self.roi_add_button.setText(_translate("SegmentationToolbox", "+"))
        self.roi_remove_button.setText(_translate("SegmentationToolbox", "-"))
        self.label.setText(_translate("SegmentationToolbox", " ⮡"))
        self.subroi_add_button.setText(_translate("SegmentationToolbox", "+"))
        self.subroi_remove_button.setText(_translate("SegmentationToolbox", "-"))
        self.autosegment_button.setText(_translate("SegmentationToolbox", "AutoSegment"))
        self.knots_group.setTitle(_translate("SegmentationToolbox", "Knots"))
        self.addknot_button.setText(_translate("SegmentationToolbox", "Add/Move"))
        self.removeknot_button.setText(_translate("SegmentationToolbox", "Remove"))
        self.removeall_button.setText(_translate("SegmentationToolbox", "Clear"))
        self.menuFile.setTitle(_translate("SegmentationToolbox", "File..."))
        self.actionSave_masks.setText(_translate("SegmentationToolbox", "Save masks..."))
        self.actionImport_ROIs.setText(_translate("SegmentationToolbox", "Import ROI file..."))
        self.actionExport_ROI_file.setText(_translate("SegmentationToolbox", "Export ROI file..."))
        self.actionImport_masks.setText(_translate("SegmentationToolbox", "Import masks..."))
